apiVersion: v1
kind: Secret
metadata:
  name: chronograf
  namespace: "{{ chronograf_namespace.namespace }}"
data:
{% for key, value in chronograf_influxdb_database.items() %}
  {{ key }}: |-
    {
{% for k, v in value %}
      "{{ k }}": "{{ v }}"{% if not loop.last %},{% endif %}
{% endfor %}
    }{% if not loop.last %},{% endif %}
{% endfor %}
